version: '3.8'

services:
  openfire:
    build:
      context: ./docker/openfire
    container_name: war-rooms-openfire
    restart: unless-stopped
    ports:
      - "9090:9090"  # Admin console
      - "5222:5222"  # XMPP client connections
      - "7070:7070"  # HTTP binding (BOSH)
      - "7443:7443"  # HTTPS binding
      - "5269:5269"  # Server-to-server
    volumes:
      - openfire-data:/var/lib/openfire
      - openfire-logs:/var/log/openfire
    environment:
      - JAVA_OPTIONS=-Xms512m -Xmx1024m
    networks:
      - war-rooms-network

networks:
  war-rooms-network:
    driver: bridge

volumes:
  openfire-data:
  openfire-logs:
